# Generated by Django 5.0.3 on 2024-05-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_hotels_options_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='Theme',
            new_name='theme',
        ),
        migrations.AddField(
            model_name='tickets',
            name='count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
