# Generated by Django 5.0.3 on 2024-05-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_theme_schedule_theme_tickets_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotels',
            options={'ordering': ['name'], 'verbose_name': 'Hotels', 'verbose_name_plural': 'Hotels'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['first_name'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedule'},
        ),
        migrations.AlterModelOptions(
            name='speakers',
            options={'ordering': ['first_name'], 'verbose_name': 'Speakers', 'verbose_name_plural': 'Speakers'},
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={'ordering': ['id'], 'verbose_name': 'Tickets', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AddIndex(
            model_name='hotels',
            index=models.Index(fields=['name'], name='event_hotel_name_9c3958_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['first_name'], name='event_sched_first_n_0a1b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='speakers',
            index=models.Index(fields=['first_name'], name='event_speak_first_n_7efd52_idx'),
        ),
        migrations.AddIndex(
            model_name='tickets',
            index=models.Index(fields=['id'], name='event_ticke_id_c01b16_idx'),
        ),
    ]
